In [65]:
from selenium import webdriver
import time
import requests
from selenium.webdriver.common.keys import Keys
from bs4 import BeautifulSoup as bs
import lxml

In [66]:
options = webdriver.ChromeOptions()

options.add_argument('headless')

options.add_argument('window-size=1920x1080')

path = 'C:\\Users\\LENOVO\\Desktop\\Growth Hackers\\Session\\session_05. 데이터 수집과 관리\\session_05 실습코드\\chromedriver.exe'

driver = webdriver.Chrome(path, options=options)

driver.implicitly_wait(3)

driver.get("http://www.kobis.or.kr/kobis/business/stat/boxs/findDailyBoxOfficeList.do?loadEnd=0&searchType=search&sSearchFrom=2019-03-24&sSearchTo=2019-03-30&sMultiMovieYn=&sRepNationCd=&sWideAreaCd=")

driver.implicitly_wait(4)

driver.find_element_by_id("btn_0").click()

driver.implicitly_wait(2)

driver.find_element_by_id("btn_0").click()

driver.implicitly_wait(2)

driver.find_element_by_id("btn_0").click()

driver.implicitly_wait(2)

driver.find_element_by_id("btn_0").click()

daily_boxoffice_html = driver.page_source

In [67]:
parsed_daily_boxoffice_html = bs(daily_boxoffice_html, 'html.parser')

daily_boxoffice_30 = parsed_daily_boxoffice_html.find("tbody", {"id":"tbody_0"})

movie_list_30 = daily_boxoffice_30.find_all("tr")

In [68]:
import pandas as pd

daily_movies_30 = {'영화명' : [],
'순위 변동' : [],
'개봉일' : [],
'매출액' : [],
'매출액점유율' : [],
'관객수' : [],
'누적관객수' : [],
'스크린수' : [],
'상영횟수' : []}

for movie in movie_list_30:
    title_rank = movie.find("td").find_next_sibling("td").text
    daily_movies_30['영화명'].append(title_rank[:-5].strip())
    daily_movies_30['순위 변동'].append(title_rank[-4:].strip())
    daily_movies_30['개봉일'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_30['매출액'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_30['매출액점유율'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_30['관객수'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_30['누적관객수'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_30['스크린수'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_30['상영횟수'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())

In [69]:
daily_boxoffice_30 = pd.DataFrame(daily_movies_30) 

daily_boxoffice_30.head()

,영화명,순위 변동,개봉일,매출액,매출액점유율,관객수,누적관객수,스크린수,상영횟수
0,어스,동일,2019-03-27,"2,528,527,731",36.3%,"275,451","717,812","1,132","5,487"
1,돈,동일,2019-03-20,"2,295,707,570",32.9%,"256,035","2,441,353","1,157","5,736"
2,덤보,2상승,2019-03-27,"660,853,559",9.5%,"78,695","132,249",761,"2,200"
3,캡틴 마블,1하락,2019-03-06,"675,853,110",9.7%,"77,530","5,473,771",619,"1,895"
4,장난스런 키스,1하락,2019-03-27,"383,004,241",5.5%,"46,032","121,934",482,"1,186"

In [70]:
def change_rank(rank):
    if rank == "동일":
        rank = 0
    elif rank[-2:] == "하락":
        rank = int(rank[:-2]) * -1
    elif rank[-2:] == "상승":
        rank = int(rank[:-2]) * 1
    return rank

daily_boxoffice_30['순위 변동'] = daily_boxoffice_30['순위 변동'].map(lambda x: change_rank(x))


daily_boxoffice_30.head()

,영화명,순위 변동,개봉일,매출액,매출액점유율,관객수,누적관객수,스크린수,상영횟수
0,어스,0,2019-03-27,"2,528,527,731",36.3%,"275,451","717,812","1,132","5,487"
1,돈,0,2019-03-20,"2,295,707,570",32.9%,"256,035","2,441,353","1,157","5,736"
2,덤보,2,2019-03-27,"660,853,559",9.5%,"78,695","132,249",761,"2,200"
3,캡틴 마블,-1,2019-03-06,"675,853,110",9.7%,"77,530","5,473,771",619,"1,895"
4,장난스런 키스,-1,2019-03-27,"383,004,241",5.5%,"46,032","121,934",482,"1,186"

In [71]:
driver.find_element_by_id("btn_106").click()

driver.implicitly_wait(2)

driver.find_element_by_id("btn_106").click()

driver.implicitly_wait(2)

driver.find_element_by_id("btn_106").click()

driver.implicitly_wait(2)

driver.find_element_by_id("btn_106").click()

daily_boxoffice_html = driver.page_source

parsed_daily_boxoffice_html = bs(daily_boxoffice_html, 'html.parser')

daily_boxoffice_29 = parsed_daily_boxoffice_html.find("tbody", {"id":"tbody_106"})

movie_list_29 = daily_boxoffice_29.find_all("tr")

daily_movies_29 = {'영화명' : [],
'순위 변동' : [],
'개봉일' : [],
'매출액' : [],
'매출액점유율' : [],
'관객수' : [],
'누적관객수' : [],
'스크린수' : [],
'상영횟수' : []}

for movie in movie_list_29:
    title_rank = movie.find("td").find_next_sibling("td").text
    daily_movies_29['영화명'].append(title_rank[:-5].strip())
    daily_movies_29['순위 변동'].append(title_rank[-4:].strip())
    daily_movies_29['개봉일'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_29['매출액'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_29['매출액점유율'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_29['관객수'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_29['누적관객수'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_29['스크린수'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_29['상영횟수'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    
daily_boxoffice_29 = pd.DataFrame(daily_movies_29) 

def change_rank(rank):
    if rank == "동일":
        rank = 0
    elif rank[-2:] == "하락":
        rank = int(rank[:-2]) * -1
    elif rank[-2:] == "상승":
        rank = int(rank[:-2]) * 1
    return rank

daily_boxoffice_29['순위 변동'] = daily_boxoffice_29['순위 변동'].map(lambda x: change_rank(x))


daily_boxoffice_29.head()

,영화명,순위 변동,개봉일,매출액,매출액점유율,관객수,누적관객수,스크린수,상영횟수
0,어스,0,2019-03-27,"1,252,009,864",39.1%,"134,576","442,361","1,066","5,039"
1,돈,0,2019-03-20,"1,039,861,023",32.5%,"117,579","2,185,318","1,112","5,321"
2,캡틴 마블,0,2019-03-06,"271,653,717",8.5%,"30,748","5,396,241",571,"1,715"
3,장난스런 키스,0,2019-03-27,"183,348,717",5.7%,"21,064","75,902",478,"1,213"
4,덤보,0,2019-03-27,"146,237,293",4.6%,"16,537","53,554",595,"1,700"

In [73]:
driver.find_element_by_id("btn_211").click()

driver.implicitly_wait(2)

driver.find_element_by_id("btn_211").click()

driver.implicitly_wait(2)

driver.find_element_by_id("btn_211").click()

driver.implicitly_wait(2)

driver.find_element_by_id("btn_211").click()

daily_boxoffice_html = driver.page_source

parsed_daily_boxoffice_html = bs(daily_boxoffice_html, 'html.parser')

daily_boxoffice_28 = parsed_daily_boxoffice_html.find("tbody", {"id":"tbody_211"})

movie_list_28 = daily_boxoffice_28.find_all("tr")

daily_movies_28 = {'영화명' : [],
'순위 변동' : [],
'개봉일' : [],
'매출액' : [],
'매출액점유율' : [],
'관객수' : [],
'누적관객수' : [],
'스크린수' : [],
'상영횟수' : []}

for movie in movie_list_28:
    title_rank = movie.find("td").find_next_sibling("td").text
    daily_movies_28['영화명'].append(title_rank[:-5].strip())
    daily_movies_28['순위 변동'].append(title_rank[-4:].strip())
    daily_movies_28['개봉일'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_28['매출액'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_28['매출액점유율'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_28['관객수'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_28['누적관객수'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_28['스크린수'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_28['상영횟수'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    
daily_boxoffice_28 = pd.DataFrame(daily_movies_28) 

daily_boxoffice_28.head()

def change_rank(rank):
    if rank == "동일":
        rank = 0
    elif rank[-2:] == "하락":
        rank = int(rank[:-2]) * -1
    elif rank[-2:] == "상승":
        rank = int(rank[:-2]) * 1
    return rank

daily_boxoffice_28['순위 변동'] = daily_boxoffice_28['순위 변동'].map(lambda x: change_rank(x))


daily_boxoffice_28.head()

,영화명,순위 변동,개봉일,매출액,매출액점유율,관객수,누적관객수,스크린수,상영횟수
0,어스,0,2019-03-27,"804,472,970",34.2%,"93,775","307,785","1,008","4,701"
1,돈,0,2019-03-20,"722,941,410",30.8%,"89,657","2,067,739","1,037","4,985"
2,캡틴 마블,0,2019-03-06,"194,516,210",8.3%,"23,510","5,365,493",552,"1,616"
3,장난스런 키스,0,2019-03-27,"120,300,990",5.1%,"14,808","54,838",475,"1,175"
4,덤보,0,2019-03-27,"96,581,130",4.1%,"11,990","37,017",564,"1,660"

In [75]:
driver.find_element_by_id("btn_334").click()

driver.implicitly_wait(2)

driver.find_element_by_id("btn_334").click()

driver.implicitly_wait(2)

driver.find_element_by_id("btn_334").click()

driver.implicitly_wait(2)

driver.find_element_by_id("btn_334").click()

daily_boxoffice_html = driver.page_source

parsed_daily_boxoffice_html = bs(daily_boxoffice_html, 'html.parser')

daily_boxoffice_27 = parsed_daily_boxoffice_html.find("tbody", {"id":"tbody_334"})

movie_list_27 = daily_boxoffice_27.find_all("tr")

daily_movies_27 = {'영화명' : [],
'순위 변동' : [],
'개봉일' : [],
'매출액' : [],
'매출액점유율' : [],
'관객수' : [],
'누적관객수' : [],
'스크린수' : [],
'상영횟수' : []}

for movie in movie_list_27:
    title_rank = movie.find("td").find_next_sibling("td").text
    daily_movies_27['영화명'].append(title_rank[:-5].strip())
    daily_movies_27['순위 변동'].append(title_rank[-4:].strip())
    daily_movies_27['개봉일'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_27['매출액'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_27['매출액점유율'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_27['관객수'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_27['누적관객수'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_27['스크린수'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_27['상영횟수'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    
daily_boxoffice_27 = pd.DataFrame(daily_movies_27) 

daily_boxoffice_27.head()

def change_rank(rank):
    if rank == "동일":
        rank = 0
    elif rank[-2:] == "하락":
        rank = int(rank[:-2]) * -1
    elif rank[-2:] == "상승":
        rank = int(rank[:-2]) * 1
    return rank

daily_boxoffice_27['순위 변동'] = daily_boxoffice_27['순위 변동'].map(lambda x: change_rank(x))


daily_boxoffice_27.head()

,영화명,순위 변동,개봉일,매출액,매출액점유율,관객수,누적관객수,스크린수,상영횟수
0,어스,New,2019-03-27,"1,319,500,490",38.0%,"213,624","214,010","1,084","4,898"
1,돈,-1,2019-03-20,"1,205,032,190",34.7%,"204,620","1,978,082","1,119","5,122"
2,캡틴 마블,-1,2019-03-06,"275,468,410",7.9%,"46,506","5,341,983",636,"1,848"
3,장난스런 키스,1,2019-03-27,"178,833,530",5.2%,"30,692","40,030",488,"1,198"
4,덤보,1,2019-03-27,"143,508,030",4.1%,"24,835","25,027",569,"1,077"

In [76]:
driver.find_element_by_id("btn_460").click()

driver.implicitly_wait(2)

driver.find_element_by_id("btn_460").click()

driver.implicitly_wait(2)

driver.find_element_by_id("btn_460").click()

driver.implicitly_wait(2)

driver.find_element_by_id("btn_460").click()

daily_boxoffice_html = driver.page_source

parsed_daily_boxoffice_html = bs(daily_boxoffice_html, 'html.parser')

daily_boxoffice_26 = parsed_daily_boxoffice_html.find("tbody", {"id":"tbody_460"})

movie_list_26 = daily_boxoffice_26.find_all("tr")

daily_movies_26 = {'영화명' : [],
'순위 변동' : [],
'개봉일' : [],
'매출액' : [],
'매출액점유율' : [],
'관객수' : [],
'누적관객수' : [],
'스크린수' : [],
'상영횟수' : []}

for movie in movie_list_26:
    title_rank = movie.find("td").find_next_sibling("td").text
    daily_movies_26['영화명'].append(title_rank[:-5].strip())
    daily_movies_26['순위 변동'].append(title_rank[-4:].strip())
    daily_movies_26['개봉일'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_26['매출액'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_26['매출액점유율'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_26['관객수'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_26['누적관객수'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_26['스크린수'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_26['상영횟수'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    
daily_boxoffice_26 = pd.DataFrame(daily_movies_26) 

daily_boxoffice_26.head()

def change_rank(rank):
    if rank == "동일":
        rank = 0
    elif rank[-2:] == "하락":
        rank = int(rank[:-2]) * -1
    elif rank[-2:] == "상승":
        rank = int(rank[:-2]) * 1
    return rank

daily_boxoffice_26['순위 변동'] = daily_boxoffice_26['순위 변동'].map(lambda x: change_rank(x))


daily_boxoffice_26.head()

,영화명,순위 변동,개봉일,매출액,매출액점유율,관객수,누적관객수,스크린수,상영횟수
0,돈,0,2019-03-20,"890,831,280",55.8%,"110,062","1,773,462","1,344","6,942"
1,캡틴 마블,0,2019-03-06,"249,453,760",15.6%,"29,769","5,295,477",806,"3,285"
2,악질경찰,0,2019-03-20,"135,373,220",8.5%,"16,565","224,861",691,"2,345"
3,우상,0,2019-03-20,"82,757,900",5.2%,"10,031","157,829",616,"1,700"
4,이스케이프 룸,0,2019-03-14,"52,724,540",3.3%,"6,261","557,876",421,945

In [77]:
driver.find_element_by_id("btn_574").click()

driver.implicitly_wait(2)

driver.find_element_by_id("btn_574").click()

driver.implicitly_wait(2)

driver.find_element_by_id("btn_574").click()

driver.implicitly_wait(2)

driver.find_element_by_id("btn_574").click()

daily_boxoffice_html = driver.page_source

parsed_daily_boxoffice_html = bs(daily_boxoffice_html, 'html.parser')

daily_boxoffice_25 = parsed_daily_boxoffice_html.find("tbody", {"id":"tbody_574"})

movie_list_25 = daily_boxoffice_25.find_all("tr")

daily_movies_25 = {'영화명' : [],
'순위 변동' : [],
'개봉일' : [],
'매출액' : [],
'매출액점유율' : [],
'관객수' : [],
'누적관객수' : [],
'스크린수' : [],
'상영횟수' : []}

for movie in movie_list_25:
    title_rank = movie.find("td").find_next_sibling("td").text
    daily_movies_25['영화명'].append(title_rank[:-5].strip())
    daily_movies_25['순위 변동'].append(title_rank[-4:].strip())
    daily_movies_25['개봉일'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_25['매출액'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_25['매출액점유율'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_25['관객수'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_25['누적관객수'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_25['스크린수'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_25['상영횟수'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    
daily_boxoffice_25 = pd.DataFrame(daily_movies_25) 

daily_boxoffice_25.head()

def change_rank(rank):
    if rank == "동일":
        rank = 0
    elif rank[-2:] == "하락":
        rank = int(rank[:-2]) * -1
    elif rank[-2:] == "상승":
        rank = int(rank[:-2]) * 1
    return rank

daily_boxoffice_25['순위 변동'] = daily_boxoffice_25['순위 변동'].map(lambda x: change_rank(x))


daily_boxoffice_25.head()

,영화명,순위 변동,개봉일,매출액,매출액점유율,관객수,누적관객수,스크린수,상영횟수
0,돈,0,2019-03-20,"1,042,451,680",59.0%,"126,999","1,663,400","1,330","6,948"
1,캡틴 마블,0,2019-03-06,"277,223,930",15.7%,"32,899","5,265,708",785,"3,330"
2,악질경찰,0,2019-03-20,"153,190,910",8.7%,"18,692","208,296",687,"2,381"
3,우상,0,2019-03-20,"81,839,880",4.6%,"9,918","147,798",590,"1,741"
4,이스케이프 룸,0,2019-03-14,"60,514,470",3.4%,"7,153","551,615",415,967

In [78]:
driver.find_element_by_id("btn_679").click()

driver.implicitly_wait(2)

driver.find_element_by_id("btn_679").click()

driver.implicitly_wait(2)

driver.find_element_by_id("btn_679").click()

driver.implicitly_wait(2)

driver.find_element_by_id("btn_679").click()

daily_boxoffice_html = driver.page_source

parsed_daily_boxoffice_html = bs(daily_boxoffice_html, 'html.parser')

daily_boxoffice_24 = parsed_daily_boxoffice_html.find("tbody", {"id":"tbody_679"})

movie_list_24 = daily_boxoffice_24.find_all("tr")

daily_movies_24 = {'영화명' : [],
'순위 변동' : [],
'개봉일' : [],
'매출액' : [],
'매출액점유율' : [],
'관객수' : [],
'누적관객수' : [],
'스크린수' : [],
'상영횟수' : []}

for movie in movie_list_24:
    title_rank = movie.find("td").find_next_sibling("td").text
    daily_movies_24['영화명'].append(title_rank[:-5].strip())
    daily_movies_24['순위 변동'].append(title_rank[-4:].strip())
    daily_movies_24['개봉일'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_24['매출액'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_24['매출액점유율'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_24['관객수'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_24['누적관객수'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_24['스크린수'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    daily_movies_24['상영횟수'].append(movie.find("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").find_next_sibling("td").text.strip())
    
daily_boxoffice_24 = pd.DataFrame(daily_movies_24) 

daily_boxoffice_24.head()

def change_rank(rank):
    if rank == "동일":
        rank = 0
    elif rank[-2:] == "하락":
        rank = int(rank[:-2]) * -1
    elif rank[-2:] == "상승":
        rank = int(rank[:-2]) * 1
    return rank

daily_boxoffice_24['순위 변동'] = daily_boxoffice_24['순위 변동'].map(lambda x: change_rank(x))


daily_boxoffice_24.head()

,영화명,순위 변동,개봉일,매출액,매출액점유율,관객수,누적관객수,스크린수,상영횟수
0,돈,0,2019-03-20,"3,753,473,160",59.7%,"416,173","1,536,401","1,431","7,433"
1,캡틴 마블,0,2019-03-06,"1,275,765,220",20.3%,"142,380","5,232,809",947,"3,768"
2,악질경찰,0,2019-03-20,"427,941,590",6.8%,"46,589","189,604",718,"2,513"
3,우상,0,2019-03-20,"254,358,090",4.0%,"28,126","137,880",659,"1,884"
4,이스케이프 룸,0,2019-03-14,"214,363,930",3.4%,"23,494","544,462",491,"1,060"

In [79]:
import sqlite3

con = sqlite3.connect("daily_boxoffice.db")

In [81]:
con.execute("CREATE TABLE daily_boxoffice_30(title text, rank int, open text, earning int, earning_share text, audiences int, total_audiences int, num_screen int, num_play int)")
daily_boxoffice_30.to_sql("daily_boxoffice_30", con, chunksize=1000, if_exists='replace')

C:\Users\LENOVO\Anaconda3\lib\site-packages\pandas\core\generic.py:2130: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  dtype=dtype)

In [82]:
con.execute("CREATE TABLE daily_boxoffice_29(title text, rank int, open text, earning int, earning_share text, audiences int, total_audiences int, num_screen int, num_play int)")
daily_boxoffice_29.to_sql("daily_boxoffice_29", con, chunksize=1000, if_exists='replace')

In [83]:
con.execute("CREATE TABLE daily_boxoffice_28(title text, rank int, open text, earning int, earning_share text, audiences int, total_audiences int, num_screen int, num_play int)")
daily_boxoffice_28.to_sql("daily_boxoffice_28", con, chunksize=1000, if_exists='replace')

In [84]:
con.execute("CREATE TABLE daily_boxoffice_27(title text, rank int, open text, earning int, earning_share text, audiences int, total_audiences int, num_screen int, num_play int)")
daily_boxoffice_27.to_sql("daily_boxoffice_27", con, chunksize=1000, if_exists='replace')

In [85]:
con.execute("CREATE TABLE daily_boxoffice_26(title text, rank int, open text, earning int, earning_share text, audiences int, total_audiences int, num_screen int, num_play int)")
daily_boxoffice_26.to_sql("daily_boxoffice_26", con, chunksize=1000, if_exists='replace')

In [86]:
con.execute("CREATE TABLE daily_boxoffice_25(title text, rank int, open text, earning int, earning_share text, audiences int, total_audiences int, num_screen int, num_play int)")
daily_boxoffice_25.to_sql("daily_boxoffice_25", con, chunksize=1000, if_exists='replace')

In [87]:
con.execute("CREATE TABLE daily_boxoffice_24(title text, rank int, open text, earning int, earning_share text, audiences int, total_audiences int, num_screen int, num_play int)")
daily_boxoffice_24.to_sql("daily_boxoffice_24", con, chunksize=1000, if_exists='replace')

In [88]:
con.commit()

con.close

In [90]:

con = sqlite3.connect("daily_boxoffice.db")

cursor = con.cursor()

cursor.execute("SELECT * FROM daily_boxoffice_26")

data = cursor.fetchall()

pd.DataFrame(data).head()

,0,1,2,3,4,5,6,7,8,9
0,0,돈,0,2019-03-20,"890,831,280",55.8%,"110,062","1,773,462","1,344","6,942"
1,1,캡틴 마블,0,2019-03-06,"249,453,760",15.6%,"29,769","5,295,477",806,"3,285"
2,2,악질경찰,0,2019-03-20,"135,373,220",8.5%,"16,565","224,861",691,"2,345"
3,3,우상,0,2019-03-20,"82,757,900",5.2%,"10,031","157,829",616,"1,700"
4,4,이스케이프 룸,0,2019-03-14,"52,724,540",3.3%,"6,261","557,876",421,945

In [92]:
cursor.execute("SELECT * FROM daily_boxoffice_25")

data = cursor.fetchall()

df = pd.read_sql("SELECT * FROM daily_boxoffice_25", con, index_col='index')

df.head()

,영화명,순위 변동,개봉일,매출액,매출액점유율,관객수,누적관객수,스크린수,상영횟수
index,,,,,,,,,
0,돈,0,2019-03-20,"1,042,451,680",59.0%,"126,999","1,663,400","1,330","6,948"
1,캡틴 마블,0,2019-03-06,"277,223,930",15.7%,"32,899","5,265,708",785,"3,330"
2,악질경찰,0,2019-03-20,"153,190,910",8.7%,"18,692","208,296",687,"2,381"
3,우상,0,2019-03-20,"81,839,880",4.6%,"9,918","147,798",590,"1,741"
4,이스케이프 룸,0,2019-03-14,"60,514,470",3.4%,"7,153","551,615",415,967